Repository mezidia/medivac, pull requests merged in 2021-09, with the labels that each got.

#1 Tkinter implemention
  app.py
Labels: enhancement

#2 Sqlite
  .gitignore
  models.py
  sqlite/__init__.py
  sqlite/alchemy_example.py
  sqlite/connector.py
  sqlite/example.py
Labels: enhancement

#3 ❄️ SQLalchemy added ❄️
  docs/postgreSQL/main.py
  postgresql/config.py
  postgresql/connector.py
  postgresql/example.py
Labels: bug

#6 VsIG-MySQL-CRUD-1
  .gitignore
  mysql/connector.py
  mysql/example.py
Labels: bug

#5 Mkdocs
  .github/workflows/docs.yml
  docs/autostation.md
  docs/index.md
  docs/mysql.md
  docs/postgresql.md
  docs/sqlite.md
  mkdocs.yml
  requirements.txt
Labels: documentation, enhancement

#7 Update tkinter
  app.py
  mysql_api/__init__.py
  mysql_api/config.py
  mysql_api/connector.py
  mysql_api/example.py
  postgresql_api/__init__.py
  postgresql_api/config.py
  postgresql_api/connector.py
  postgresql_api/example.py
  sqlite_api/__init__.py
  sqlite_api/alchemy_example.py
  sqlite_api/connector.py
  sqlite_api/example.py
Labels: enhancement
